# SPDX-FileCopyrightText: 2023 Sefa Eyeoglu <contact@scrumplex.net>
#
# SPDX-License-Identifier: MIT

name: Update lockfiles

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-locks:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set Git user info
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          # See https://github.com/berberman/nvfetcher/issues/133
          export LANG=C.UTF-8

      - name: Update flake inputs
        run: |
          nix flake update --commit-lock-file

      - name: Update upstream sources
        run: |
          nix develop --accept-flake-config -c nvfetcher --commit-changes

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          base: "main"
          branch: "update-locks"
          delete-branch: true
          title: "chore: update locks"
          body: "Automated pull request to update flake.lock and nvfetcher sources"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
